export default{
	emoj:{
		baseURL:'http://webot-data.cn-gd.ufileos.com',
		emojs:[
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/00.png',sign:'[微笑]',code: '/::)'},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/01.png',sign:'[撇嘴]',code: '/::~'},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/02.png',sign:'[色]',code: '/::B'},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/03.png',sign:'[发呆]',code: '/::|'},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/04.png',sign:'[得意]',code: '/:8-)'},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/05.png',sign:'[流泪]',code: '/::<'},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/06.png',sign:'[害羞]',code: '/::$'},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/07.png',sign:'[闭嘴]',code: '/::X'},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/08.png',sign:'[睡]',code: '/::Z'},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/09.png',sign:'[大哭]',code: "/::'("},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/10.png',sign:"[尴尬]",code:"/::-|"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/11.png',sign:"[发怒]",code:"/::@"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/12.png',sign:"[调皮]",code:"/::P"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/13.png',sign:"[呲牙]",code:"/::D"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/14.png',sign:"[惊讶]",code:"/::O"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/15.png',sign:"[难过]",code:"/::("},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/17.png',sign:"[囧]",code:"[囧]"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/18.png',sign:"[抓狂]",code:"/::Q"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/19.png',sign:"[吐]",code:"/::T"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/20.png',sign:"[偷笑]",code:"/:,@P"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/21.png',sign:"[愉快]",code:"/:,@-D"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/22.png',sign:"[白眼]",code:"/::d"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/23.png',sign:"[傲慢]",code:"/:,@o"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/25.png',sign:"[困]",code:"/:|-)"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/26.png',sign:"[惊恐]",code:"/::!"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/27.png',sign:"[流汗]",code:"/::L"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/28.png',sign:"[憨笑]",code:"/::>"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/29.png',sign:"[悠闲]",code:"/::,@"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/30.png',sign:"[奋斗]",code:"/:,@f"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/31.png',sign:"[咒骂]",code:"/::-S"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/32.png',sign:"[疑问]",code:"/:?"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/33.png',sign:"[嘘]",code:"/:,@x"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/34.png',sign:"[晕]",code:"/:,@@"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/36.png',sign:"[衰]",code:"/:,@!"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/37.png',sign:"[骷髅]",code:"/:!!!"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/38.png',sign:"[敲打]",code:"/:xx"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/39.png',sign:"[再见]",code:"/:bye"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/40.png',sign:"[擦汗]",code:"/:wipe"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/41.png',sign:"[抠鼻]",code:"/:dig"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/42.png',sign:"[鼓掌]",code:"/:handclap"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/44.png',sign:"[坏笑]",code:"/:B-)"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/45.png',sign:"[左哼哼]",code:"/:<@"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/46.png',sign:"[右哼哼]",code:"/:@>"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/47.png',sign:"[哈欠]",code:"/::-O"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/48.png',sign:"[鄙视]",code:"/:>-|"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/49.png',sign:"[委屈]",code:"/:P-("},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/50.png',sign:"[快哭了]",code:"/::'|"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/51.png',sign:"[阴险]",code:"/:X-)"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/52.png',sign:"[亲亲]",code:"/::*"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/54.png',sign:"[可怜]",code:"/:8*"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/55.png',sign:"[菜刀]",code:"/:pd"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/56.png',sign:"[西瓜]",code:"/:<W>"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/57.png',sign:"[啤酒]",code:"/:beer"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/60.png',sign:"[咖啡]",code:"/:coffee"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/62.png',sign:"[猪头]",code:"/:pig"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/63.png',sign:"[玫瑰]",code:"/:rose"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/64.png',sign:"[凋谢]",code:"/:fade"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/116.png',sign:"[嘴唇]",code:"/:showlove"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/66.png',sign:"[爱心]",code:"/:heart"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/67.png',sign:"[心碎]",code:"/:break"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/68.png',sign:"[蛋糕]",code:"/:cake"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/70.png',sign:"[炸弹]",code:"/:bome"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/74.png',sign:"[便便]",code:"/:shit"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/75.png',sign:"[月亮]",code:"/:moon"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/76.png',sign:"[太阳]",code:"/:sun"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/78.png',sign:"[拥抱]",code:"/:hug"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/79.png',sign:"[强]",code:"/:strong"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/80.png',sign:"[弱]",code:"/:weak"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/81.png',sign:"[握手]",code:"/:share"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/82.png',sign:"[胜利]",code:"/:v"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/83.png',sign:"[抱拳]",code:"/:@)"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/84.png',sign:"[勾引]",code:"/:jj"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/85.png',sign:"[拳头]",code:"/:@@"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/89.png',sign:"[OK]",code:"/:ok"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/92.png',sign:"[跳跳]",code:"/:jump"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/93.png',sign:"[发抖]",code:"/:shake"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/94.png',sign:"[怄火]",code:"/:<O>"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/95.png',sign:"[转圈]",code:"/:circle"},
			
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx1.png',sign:'[哈哈]',code:'😄',code2:''},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx2.png',sign:'[生病]',code:'😷',code2:''},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx3.png',sign:'[笑哭]',code:'😂',code2:''},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx4.png',sign:'[可爱]',code:'😝',code2:''},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx5.png',sign:'[呆住]',code:'😳',code2:''},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx6.png',sign:'[惊吓]',code:'😱',code2:''}, 
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx7.png',sign:'[失望]',code:'😔',code2:''},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx8.png',sign:'[无语]',code:'😒',code2:''},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx9.png',sign:"[嘿]",code:"[Hey]"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx10.png',sign:"[捂脸]",code:"[Facepalm]"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx11.png',sign:"[傻笑]",code:"[Smirk]"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx12.png',sign:"[聪明]",code:"[Smart]"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx13.png',sign:"[关心]",code:"[Concerned]"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx14.png',sign:"[欧耶]",code:"[Yeah!]"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx15.png',sign:'[鬼]',code:'👻',code2:''},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx16.png',sign:'[谢谢]',code:'🙏',code2:''},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx17.png',sign:'[肌肉]',code:'💪',code2:''},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx18.png',sign:'[欢迎]',code:'🎉',code2:""},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx19.png',sign:'[礼物]',code:'🎁',code2:""},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx20.png',sign:"[红包]",code:"[Packet]"},
			{uri:'http://webot-data.cn-gd.ufileos.com/emojis/wx21.png',sign:'[小鸡]',code:'[Chick]'},
		],
		emoj_regex:/😄||😷||😂||😝||😳||😱||😔||😒||👻||🙏||💪||🎉||🎁||(\[[^\]]+\]|\/:(:\)|:~|:B|:\||8-\)|:<|:\$|:X|:Z|:'\(|:-\||:@|:P|:D|:O|:\(|:Q|:T|,@P|,@-D|:d|,@o|\|-\)|:!|:L|:>|:,@|,@f|:-S|\?|,@x|,@@|,@!|!!!|xx|bye|wipe|dig|handclap|B-\)|<@|@>|:-O|>-\||P-\(|:'\||X-\)|:\*|8\*|pd|beer|coffee|pig|rose|fade|showlove|heart|break|cake|bome|shit|moon|sun|hug|strong|weak|share|v|@\)|jj|@@|ok|jump|shake|circle|<O>|<W>|[Chick]))/g,
	}
	//emoj:['😀','😃','😄','😁','😆','😅','😂','🤣','😊','😇','🙂','🙃','😉','😌','😍','😘','😗','😙','😚','😋','😜','😝','😛','🤑','🤗','🤓','😎','🤡','🤠','😏','😒','😞','😔','😟','😕','🙁','☹️','😣','😖','😫','😩','😤','😠','😡','😶','😐','😑','😯','😦','😧','😮','😲','😵','😳','😱','😨','😰','😢','😥','🤤','😭','😓','😪','😴','🙄','🤔','🤥','😬','🤐','🤢','🤧','😷','🤒','🤕'],
	
}
